/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.dependency_analysis

class OtherLibrary {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
