/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.dependency_analysis

class Library {
    fun someLibraryMethod(): Boolean {
        return OtherLibrary().someLibraryMethod()
    }
}
