/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.dependency_analysis

object TestFixture {
    fun someTestFixtureMethod(): Boolean {
        return false
    }
}
